// generated by scripts/prep_assets.py — do not edit
export type Asset = { slug: string; file: string; kind: "c" | "i" | "l" | "g"; label: string; w: number; h: number; ar: number; lum: number; paper?: number };
export const ASSETS: Record<string, Asset> = {
 "mount_black": {
  "slug": "mount_black",
  "file": "img/mount_black.png",
  "kind": "c",
  "label": "EA 4 elastic mount \u00b7 black",
  "w": 3200,
  "h": 2167,
  "ar": 1.4767,
  "lum": 0.295
 },
 "mount_nickel": {
  "slug": "mount_nickel",
  "file": "img/mount_nickel.png",
  "kind": "c",
  "label": "EA 4 elastic mount \u00b7 nickel",
  "w": 2031,
  "h": 1298,
  "ar": 1.5647,
  "lum": 0.507
 },
 "box_trio": {
  "paper": 1.0,
  "slug": "box_trio",
  "file": "img/box_trio.jpg",
  "kind": "i",
  "label": "TLM 107 \u00b7 wooden case",
  "w": 2880,
  "h": 1456,
  "ar": 1.978,
  "lum": 0.787
 },
 "heritage_vintage": {
  "paper": 0.0,
  "slug": "heritage_vintage",
  "file": "img/heritage_vintage.jpg",
  "kind": "i",
  "label": "Neumann heritage",
  "w": 2029,
  "h": 3200,
  "ar": 0.6341,
  "lum": 0.572
 },
 "nickel_ea4_stand": {
  "slug": "nickel_ea4_stand",
  "file": "img/nickel_ea4_stand.png",
  "kind": "c",
  "label": "TLM 107 nickel \u00b7 EA 4",
  "w": 2366,
  "h": 3200,
  "ar": 0.7394,
  "lum": 0.491
 },
 "nickel_front": {
  "slug": "nickel_front",
  "file": "img/nickel_front.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 nickel",
  "w": 1135,
  "h": 2400,
  "ar": 0.4729,
  "lum": 0.54
 },
 "nickel_grille_macro": {
  "paper": 0.7577940307328606,
  "slug": "nickel_grille_macro",
  "file": "img/nickel_grille_macro.jpg",
  "kind": "i",
  "label": "Head grille \u00b7 nickel",
  "w": 2676,
  "h": 2400,
  "ar": 1.115,
  "lum": 0.723
 },
 "black_ea4_brand": {
  "paper": 0.0,
  "slug": "black_ea4_brand",
  "file": "img/black_ea4_brand.jpg",
  "kind": "i",
  "label": "TLM 107 bk \u00b7 EA 4",
  "w": 3200,
  "h": 2400,
  "ar": 1.3333,
  "lum": 0.133
 },
 "nav_callouts": {
  "paper": 0.0,
  "slug": "nav_callouts",
  "file": "img/nav_callouts.jpg",
  "kind": "i",
  "label": "Navigation switch",
  "w": 2400,
  "h": 1292,
  "ar": 1.8576,
  "lum": 0.12
 },
 "mount_nickel_parts": {
  "slug": "mount_nickel_parts",
  "file": "img/mount_nickel_parts.png",
  "kind": "c",
  "label": "EA 4 \u00b7 nickel",
  "w": 2716,
  "h": 2716,
  "ar": 1.0,
  "lum": 0.69
 },
 "black_front": {
  "slug": "black_front",
  "file": "img/black_front.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 black",
  "w": 1534,
  "h": 3200,
  "ar": 0.4794,
  "lum": 0.268
 },
 "eco_black_mic": {
  "slug": "eco_black_mic",
  "file": "img/eco_black_mic.png",
  "kind": "c",
  "label": "Neumann studio microphone",
  "w": 1026,
  "h": 3200,
  "ar": 0.3206,
  "lum": 0.261
 },
 "nickel_clip_angle": {
  "slug": "nickel_clip_angle",
  "file": "img/nickel_clip_angle.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 nickel",
  "w": 1613,
  "h": 2232,
  "ar": 0.7227,
  "lum": 0.487
 },
 "black_xlr_angle": {
  "slug": "black_xlr_angle",
  "file": "img/black_xlr_angle.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 black",
  "w": 2167,
  "h": 2319,
  "ar": 0.9345,
  "lum": 0.221
 },
 "white_ea4": {
  "slug": "white_ea4",
  "file": "img/white_ea4.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 EA 4",
  "w": 1933,
  "h": 3200,
  "ar": 0.6041,
  "lum": 0.747
 },
 "nickel_console": {
  "paper": 0.01955295138888889,
  "slug": "nickel_console",
  "file": "img/nickel_console.jpg",
  "kind": "i",
  "label": "TLM 107 in the studio",
  "w": 2560,
  "h": 3200,
  "ar": 0.8,
  "lum": 0.376
 },
 "nickel_purple": {
  "paper": 0.0,
  "slug": "nickel_purple",
  "file": "img/nickel_purple.jpg",
  "kind": "i",
  "label": "TLM 107 \u00b7 nickel",
  "w": 2133,
  "h": 3200,
  "ar": 0.6666,
  "lum": 0.338
 },
 "logo_neumann": {
  "slug": "logo_neumann",
  "file": "img/logo_neumann.png",
  "kind": "l",
  "label": "Neumann.Berlin",
  "w": 2000,
  "h": 437,
  "ar": 4.5767,
  "lum": 0.937
 },
 "black_ea4_stand": {
  "slug": "black_ea4_stand",
  "file": "img/black_ea4_stand.png",
  "kind": "c",
  "label": "TLM 107 bk \u00b7 EA 4",
  "w": 2487,
  "h": 2676,
  "ar": 0.9294,
  "lum": 0.296
 },
 "nickel_ring_macro": {
  "paper": 0.5276921948356808,
  "slug": "nickel_ring_macro",
  "file": "img/nickel_ring_macro.jpg",
  "kind": "i",
  "label": "Control ring \u00b7 nickel",
  "w": 2920,
  "h": 2192,
  "ar": 1.3321,
  "lum": 0.729
 },
 "box_black_small": {
  "paper": 1.0,
  "slug": "box_black_small",
  "file": "img/box_black_small.jpg",
  "kind": "i",
  "label": "TLM 107 bk \u00b7 wooden case",
  "w": 1228,
  "h": 820,
  "ar": 1.4976,
  "lum": 0.753
 },
 "grille_abstract": {
  "paper": 0.0,
  "slug": "grille_abstract",
  "file": "img/grille_abstract.jpg",
  "kind": "i",
  "label": "Head grille \u00b7 black",
  "w": 3200,
  "h": 1540,
  "ar": 2.0779,
  "lum": 0.081
 },
 "u87_eco": {
  "slug": "u87_eco",
  "file": "img/u87_eco.png",
  "kind": "c",
  "label": "Neumann studio microphone",
  "w": 1719,
  "h": 2864,
  "ar": 0.6002,
  "lum": 0.597
 },
 "black_ring_macro": {
  "paper": 0.5041446596244131,
  "slug": "black_ring_macro",
  "file": "img/black_ring_macro.jpg",
  "kind": "i",
  "label": "Control ring \u00b7 black",
  "w": 2920,
  "h": 2192,
  "ar": 1.3321,
  "lum": 0.306
 },
 "nickel_front_tall": {
  "slug": "nickel_front_tall",
  "file": "img/nickel_front_tall.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 nickel",
  "w": 1498,
  "h": 3200,
  "ar": 0.4681,
  "lum": 0.651
 },
 "polar_chart": {
  "slug": "polar_chart",
  "file": "img/polar_chart.png",
  "kind": "g",
  "label": "Polar diagram",
  "w": 3148,
  "h": 3200,
  "ar": 0.9838,
  "lum": 0.466
 },
 "nickel_ea4": {
  "slug": "nickel_ea4",
  "file": "img/nickel_ea4.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 EA 4",
  "w": 2303,
  "h": 2800,
  "ar": 0.8225,
  "lum": 0.609
 },
 "badge_black_macro": {
  "paper": 0.3217002467105263,
  "slug": "badge_black_macro",
  "file": "img/badge_black_macro.jpg",
  "kind": "i",
  "label": "Neumann badge",
  "w": 2920,
  "h": 1944,
  "ar": 1.5021,
  "lum": 0.4
 },
 "grille_badge_dark": {
  "paper": 0.007195723684210526,
  "slug": "grille_badge_dark",
  "file": "img/grille_badge_dark.jpg",
  "kind": "i",
  "label": "TLM 107 bk",
  "w": 2920,
  "h": 1944,
  "ar": 1.5021,
  "lum": 0.153
 },
 "black_leds_macro": {
  "paper": 0.5074270148026315,
  "slug": "black_leds_macro",
  "file": "img/black_leds_macro.jpg",
  "kind": "i",
  "label": "Pad & pattern LEDs",
  "w": 2920,
  "h": 1944,
  "ar": 1.5021,
  "lum": 0.544
 },
 "tube_mic_psu": {
  "slug": "tube_mic_psu",
  "file": "img/tube_mic_psu.png",
  "kind": "c",
  "label": "Neumann tube microphone",
  "w": 2876,
  "h": 2920,
  "ar": 0.9849,
  "lum": 0.535
 },
 "eco_headphones_a": {
  "slug": "eco_headphones_a",
  "file": "img/eco_headphones_a.png",
  "kind": "c",
  "label": "Neumann headphones",
  "w": 2140,
  "h": 2784,
  "ar": 0.7687,
  "lum": 0.401
 },
 "eco_ma1": {
  "slug": "eco_ma1",
  "file": "img/eco_ma1.png",
  "kind": "c",
  "label": "Neumann monitor alignment",
  "w": 2235,
  "h": 2848,
  "ar": 0.7848,
  "lum": 0.255
 },
 "black_ea4": {
  "slug": "black_ea4",
  "file": "img/black_ea4.png",
  "kind": "c",
  "label": "TLM 107 bk \u00b7 EA 4",
  "w": 2471,
  "h": 2784,
  "ar": 0.8876,
  "lum": 0.261
 },
 "nickel_ea4_b": {
  "slug": "nickel_ea4_b",
  "file": "img/nickel_ea4_b.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 EA 4",
  "w": 2275,
  "h": 2680,
  "ar": 0.8489,
  "lum": 0.599
 },
 "eco_clip_kk": {
  "slug": "eco_clip_kk",
  "file": "img/eco_clip_kk.png",
  "kind": "c",
  "label": "Neumann clip microphone",
  "w": 1711,
  "h": 2833,
  "ar": 0.604,
  "lum": 0.327
 },
 "eco_monitor_a": {
  "slug": "eco_monitor_a",
  "file": "img/eco_monitor_a.png",
  "kind": "c",
  "label": "Neumann studio monitor",
  "w": 2008,
  "h": 2768,
  "ar": 0.7254,
  "lum": 0.363
 },
 "eco_monitor_b": {
  "slug": "eco_monitor_b",
  "file": "img/eco_monitor_b.png",
  "kind": "c",
  "label": "Neumann studio monitor",
  "w": 2212,
  "h": 2920,
  "ar": 0.7575,
  "lum": 0.343
 },
 "eco_headphones_b": {
  "slug": "eco_headphones_b",
  "file": "img/eco_headphones_b.png",
  "kind": "c",
  "label": "Neumann headphones",
  "w": 2096,
  "h": 2715,
  "ar": 0.772,
  "lum": 0.355
 },
 "eco_sub": {
  "slug": "eco_sub",
  "file": "img/eco_sub.png",
  "kind": "c",
  "label": "Neumann subwoofer",
  "w": 1884,
  "h": 2012,
  "ar": 0.9364,
  "lum": 0.276
 },
 "badge_black_macro2": {
  "paper": 0.3218958333333333,
  "slug": "badge_black_macro2",
  "file": "img/badge_black_macro2.jpg",
  "kind": "i",
  "label": "Neumann badge",
  "w": 1800,
  "h": 1200,
  "ar": 1.5,
  "lum": 0.4
 },
 "eco_monitor_c": {
  "slug": "eco_monitor_c",
  "file": "img/eco_monitor_c.png",
  "kind": "c",
  "label": "Neumann studio monitor",
  "w": 1876,
  "h": 2484,
  "ar": 0.7552,
  "lum": 0.394
 },
 "grille_badge_dark2": {
  "paper": 0.008333333333333333,
  "slug": "grille_badge_dark2",
  "file": "img/grille_badge_dark2.jpg",
  "kind": "i",
  "label": "TLM 107 bk",
  "w": 1800,
  "h": 1200,
  "ar": 1.5,
  "lum": 0.152
 },
 "black_leds_macro2": {
  "paper": 0.508375,
  "slug": "black_leds_macro2",
  "file": "img/black_leds_macro2.jpg",
  "kind": "i",
  "label": "Pad & pattern LEDs",
  "w": 1800,
  "h": 1200,
  "ar": 1.5,
  "lum": 0.543
 },
 "eco_hanging": {
  "slug": "eco_hanging",
  "file": "img/eco_hanging.png",
  "kind": "c",
  "label": "Neumann hanging microphone",
  "w": 364,
  "h": 1184,
  "ar": 0.3074,
  "lum": 0.303
 },
 "black_front_tall": {
  "slug": "black_front_tall",
  "file": "img/black_front_tall.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 black",
  "w": 1505,
  "h": 3200,
  "ar": 0.4703,
  "lum": 0.286
 },
 "logo_shivansh": {
  "slug": "logo_shivansh",
  "file": "img/logo_shivansh.png",
  "kind": "l",
  "label": "Shivansh Electronics",
  "w": 2372,
  "h": 714,
  "ar": 3.3221,
  "lum": 0.816
 },
 "nickel_xlr_macro": {
  "paper": 0.7347497002398081,
  "slug": "nickel_xlr_macro",
  "file": "img/nickel_xlr_macro.jpg",
  "kind": "i",
  "label": "XLR connector",
  "w": 2604,
  "h": 2400,
  "ar": 1.085,
  "lum": 0.8
 },
 "box_open_black": {
  "slug": "box_open_black",
  "file": "img/box_open_black.png",
  "kind": "c",
  "label": "Wooden case",
  "w": 2376,
  "h": 2400,
  "ar": 0.99,
  "lum": 0.176
 },
 "box_closed": {
  "slug": "box_closed",
  "file": "img/box_closed.png",
  "kind": "c",
  "label": "Wooden case",
  "w": 3200,
  "h": 1700,
  "ar": 1.8824,
  "lum": 0.199
 },
 "eco_dark_mic": {
  "slug": "eco_dark_mic",
  "file": "img/eco_dark_mic.png",
  "kind": "c",
  "label": "Neumann microphone",
  "w": 1014,
  "h": 2201,
  "ar": 0.4607,
  "lum": 0.225
 },
 "nickel_stand": {
  "slug": "nickel_stand",
  "file": "img/nickel_stand.png",
  "kind": "c",
  "label": "TLM 107 \u00b7 nickel",
  "w": 1464,
  "h": 2400,
  "ar": 0.61,
  "lum": 0.478
 },
 "cream_ea4": {
  "slug": "cream_ea4",
  "file": "img/cream_ea4.png",
  "kind": "c",
  "label": "EA 4 elastic mount",
  "w": 3200,
  "h": 3115,
  "ar": 1.0273,
  "lum": 0.666
 },
 "thumb_box_mount": {
  "paper": 1.0,
  "slug": "thumb_box_mount",
  "file": "img/thumb_box_mount.jpg",
  "kind": "i",
  "label": "TLM 107 bk \u00b7 Studio Set",
  "w": 900,
  "h": 900,
  "ar": 1.0,
  "lum": 0.666
 },
 "black_homestudio": {
  "paper": 0.01486368909512761,
  "slug": "black_homestudio",
  "file": "img/black_homestudio.jpg",
  "kind": "i",
  "label": "TLM 107 bk \u00b7 home studio",
  "w": 984,
  "h": 740,
  "ar": 1.3297,
  "lum": 0.54
 },
 "black_ring_top": {
  "paper": 1.0,
  "slug": "black_ring_top",
  "file": "img/black_ring_top.jpg",
  "kind": "i",
  "label": "Control ring \u00b7 black",
  "w": 900,
  "h": 900,
  "ar": 1.0,
  "lum": 0.455
 },
 "thumb_black_ea4": {
  "paper": 1.0,
  "slug": "thumb_black_ea4",
  "file": "img/thumb_black_ea4.jpg",
  "kind": "i",
  "label": "TLM 107 bk \u00b7 EA 4",
  "w": 892,
  "h": 904,
  "ar": 0.9867,
  "lum": 0.695
 }
};
